In [91]:
import importlib
import subprocess

import Advanced_SQL as asql
import duckdb
import SQL as sql

_ = importlib.reload(asql)
_ = importlib.reload(sql)

Use this cell to test any sql queries. This can be done in one of the following ways:

1. Fill in the `qry` within the """ """.
2. Call the question functions that you have already filled in from the SQL.py and Advanced_SQL.py files. An example of question_1 being called from the SQL.py file is currently commented out.

This cell can be copied if you wish to run multiple queries.

In [54]:
# Question 1

qry = """  
SELECT * FROM customers
"""

qry = sql.question_1()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

        Name   Surname  CustomerID
0    grayson     aziza           9
1    grayson     aziza           9
2       aria     malek          14
3       aria     malek          14
4    juliana    hunter         304
5      alina    carter         160
6     eileen  augustus         630
7     nelson     rehan         501
8      henry     noemi          98
9     alexis     amira         957
10     henry     noemi          98
11     alina    carter         160
12  scarlett     naomi         176
13    wesley    shimon         687
14  gabriela     jesse         281
15   juliana    hunter         304
16  scarlett     naomi         176
17     chavy   rebecca         370
18    nelson     rehan         501
19  gabriela     jesse         281
20    eileen  augustus         630
21    wesley    shimon         687
22     aayan     devin         888
23     chavy   rebecca         370
24     aayan     devin         888
25    alexis     amira         957
26   crystal      luna         999
27   crystal      luna         999

Should you break/incorrectly update any database tables, the database can be reset by running the following cell

In [55]:
load_script_path = "database/database_load.py"
subprocess.run(["python3", load_script_path])

CompletedProcess(args=['python3', 'database/database_load.py'], returncode=0)

In [56]:
# Question 2 

# qry = """  
# SELECT * FROM customers
# """

# Checking type of income 
# qry = "SELECT Income, typeof(Income) FROM customers"


qry = sql.question_2()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

        Name   Surname  Income
0      caden     eshal   89820
1      sadie  victoria   89647
2     amelia  theodore   89641
3     samuel    hailey   89623
4     sydney    alyssa   89603
..       ...       ...     ...
490   stella      noel   40999
491    amber    yadiel   40771
492   matias    reuben   40529
493  eliezer   richard   40513
494  cynthia     faith   40116

[495 rows x 3 columns]

In [68]:
# # Question 3

qry = "SELECT CustomerID, LoanTerm, ApprovalStatus from loans where ApprovalStatus LIKE 'Approved'"

qry = sql.question_3()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

   LoanTerm  ApprovedPercentage
0        12           48.223350
1        24           47.761194
2        36           45.108696
3        48           53.456221
4        60           45.771144

In [71]:
# # Question 3

qry = "SELECT * FROM credit"

# qry = sql.question_3()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

      CustomerID  CreditScore CustomerClass
0              1          683             B
1              2          729             A
2              3          756             A
3              4          669             B
4              5          659             B
...          ...          ...           ...
1009         996          667             B
1010         997          697             B
1011         998          665             B
1012         999          635             B
1013        1000          605             B

[1014 rows x 3 columns]

In [92]:
# Question 4

qry = "SELECT * FROM credit"

qry = sql.question_4()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

  CustomerClass  Count
0             A    487
1            A+      6
2             B    246
3             C    275

In [90]:
# Question 5

# qry = "SELECT * FROM credit WHERE CreditScore BETWEEN 600 AND 650"

qry = sql.question_5()
# qry = "SELECT * FROM credit WHERE CreditScore BETWEEN 600 AND 650"

qry = sql.question_4()

with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

  CustomerClass  Count
0             B    246
1             C    275
2            A+      6
3             A    487

# Advanced_SQL

In [ ]:
# Question 1

qry = asql.question_1()

with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set