In [122]:
import importlib
import subprocess

import Advanced_SQL as asql
import duckdb
import SQL as sql

_ = importlib.reload(asql)
_ = importlib.reload(sql)

Use this cell to test any sql queries. This can be done in one of the following ways:

1. Fill in the `qry` within the """ """.
2. Call the question functions that you have already filled in from the SQL.py and Advanced_SQL.py files. An example of question_1 being called from the SQL.py file is currently commented out.

This cell can be copied if you wish to run multiple queries.

In [54]:
# Question 1

qry = """  
SELECT * FROM customers
"""

qry = sql.question_1()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

        Name   Surname  CustomerID
0    grayson     aziza           9
1    grayson     aziza           9
2       aria     malek          14
3       aria     malek          14
4    juliana    hunter         304
5      alina    carter         160
6     eileen  augustus         630
7     nelson     rehan         501
8      henry     noemi          98
9     alexis     amira         957
10     henry     noemi          98
11     alina    carter         160
12  scarlett     naomi         176
13    wesley    shimon         687
14  gabriela     jesse         281
15   juliana    hunter         304
16  scarlett     naomi         176
17     chavy   rebecca         370
18    nelson     rehan         501
19  gabriela     jesse         281
20    eileen  augustus         630
21    wesley    shimon         687
22     aayan     devin         888
23     chavy   rebecca         370
24     aayan     devin         888
25    alexis     amira         957
26   crystal      luna         999
27   crystal      luna         999

Should you break/incorrectly update any database tables, the database can be reset by running the following cell

In [55]:
load_script_path = "database/database_load.py"
subprocess.run(["python3", load_script_path])

CompletedProcess(args=['python3', 'database/database_load.py'], returncode=0)

In [56]:
# Question 2 

# qry = """  
# SELECT * FROM customers
# """

# Checking type of income 
# qry = "SELECT Income, typeof(Income) FROM customers"


qry = sql.question_2()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

        Name   Surname  Income
0      caden     eshal   89820
1      sadie  victoria   89647
2     amelia  theodore   89641
3     samuel    hailey   89623
4     sydney    alyssa   89603
..       ...       ...     ...
490   stella      noel   40999
491    amber    yadiel   40771
492   matias    reuben   40529
493  eliezer   richard   40513
494  cynthia     faith   40116

[495 rows x 3 columns]

In [68]:
# # Question 3

qry = "SELECT CustomerID, LoanTerm, ApprovalStatus from loans where ApprovalStatus LIKE 'Approved'"

qry = sql.question_3()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

   LoanTerm  ApprovedPercentage
0        12           48.223350
1        24           47.761194
2        36           45.108696
3        48           53.456221
4        60           45.771144

In [71]:
# # Question 3

qry = "SELECT * FROM credit"

# qry = sql.question_3()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

      CustomerID  CreditScore CustomerClass
0              1          683             B
1              2          729             A
2              3          756             A
3              4          669             B
4              5          659             B
...          ...          ...           ...
1009         996          667             B
1010         997          697             B
1011         998          665             B
1012         999          635             B
1013        1000          605             B

[1014 rows x 3 columns]

In [92]:
# Question 4

qry = "SELECT * FROM credit"

qry = sql.question_4()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

  CustomerClass  Count
0             A    487
1            A+      6
2             B    246
3             C    275

In [90]:
# Question 5

# qry = "SELECT * FROM credit WHERE CreditScore BETWEEN 600 AND 650"

qry = sql.question_5()
# qry = "SELECT * FROM credit WHERE CreditScore BETWEEN 600 AND 650"

qry = sql.question_4()

with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

  CustomerClass  Count
0             B    246
1             C    275
2            A+      6
3             A    487

# Advanced_SQL

In [220]:
import importlib
import subprocess

import Advanced_SQL as asql
import duckdb
import SQL as sql

_ = importlib.reload(asql)
_ = importlib.reload(sql)

In [100]:
# Question 1

qry = "SELECT * FROM customers"
qry = asql.question_1()

with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

  CustomerClass  AverageIncome
0             B   64950.695473
1             C   64665.047970
2            A+   76921.000000
3             A   64117.110417

In [142]:
# Question 2

# qry = "SELECT * FROM customers"
# qry = "SELECT * FROM customers WHERE Region = 'FreeState'"
qry = asql.question_2()

# qry = "SELECT DISTINCT COUNT(*) FROM loans WHERE ApprovalStatus = 'Rejected'" 
with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

        Province  RejectedApplications
0     Mpumalanga                    67
1    EasternCape                    65
2        Gauteng                    65
3    WesternCape                    58
4        Limpopo                    55
5    NorthenCape                    51
6  KwaZulu-Natal                    51
7      FreeState                    51
8      NorthWest                    50
9   NorthernCape                     5

In [156]:
# Question 3

# qry = "SELECT * FROM customers"
# qry = "SELECT DISTINCT TYPEOF(CreditScore) FROM credit"
qry = asql.question_3()
qry = "SELECT * FROM financing"

# qry = "SELECT DISTINCT COUNT(*) FROM loans WHERE ApprovalStatus = 'Rejected'" 
with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

,CustomerID,Income,LoanAmount,LoanTerm,InterestRate,ApprovalStatus,CreditScore
0,4,48926,15511,48,6.22,Rejected,669
1,7,56049,21327,48,6.68,Rejected,768
2,12,40729,15325,36,8.04,Approved,692
3,17,49692,14617,36,6.97,Rejected,673
4,18,86498,25399,48,6.54,Rejected,665
...,...,...,...,...,...,...,...
995,907,70825,27497,24,5.91,Approved,636
996,924,53067,29450,12,4.46,Approved,610
997,926,64981,16346,36,4.05,Rejected,617
998,932,89450,19729,12,5.01,Rejected,797
999,999,52113,21366,24,4.33,Approved,635

In [ ]:
# Question 4

# qry = "SELECT * FROM customers"
qry = asql.question_4()
# qry = "SELECT DISTINCT TimeZone FROM repayments"
# qry = "SELECT * FROM months"
def hour_to_min(hours):
    return hours*60
qry = "SELECT COUNT(*) FROM timeline WHERE CustomerID = 1"
# qry = "SELECT DISTINCT COUNT(*) FROM loans WHERE ApprovalStatus = 'Rejected'" 
with duckdb.connect("database/loan.db") as cursor:
    cursor.execute("DROP TABLE IF EXISTS timeline")
    result_set = cursor.execute(qry).df()

result_set

   count_star()
0            12

In [ ]:
# Question 5

qry = asql.question_5()
# qry = "SELECT DISTINCT(MonthName) FROM timeline"
with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

,CustomerID,JanuaryRepayments,JanuaryTotal,FebruaryRepayments,FebruaryTotal,MarchRepayments,MarchTotal,MayRepayments,MayTotal,AprilRepayments,...,AugustRepayments,AugustTotal,SeptemberRepayments,SeptemberTotal,OctoberRepayments,OctoberTotal,NovemberRepayments,NovemberTotal,DecemberRepayments,DecemberTotal
0,1,0,0.0,0,0.0,0,0.0,0,0.0,1,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
1,2,1,359.0,0,0.0,1,352.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,1,58.0
2,3,2,413.0,0,0.0,1,154.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
3,4,0,0.0,0,0.0,0,0.0,0,0.0,0,...,0,0.0,1,123.0,1,315.0,0,0.0,0,0.0
4,5,0,0.0,0,0.0,0,0.0,0,0.0,1,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,0,0.0,0,0.0,0,0.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
996,997,0,0.0,0,0.0,0,0.0,0,0.0,0,...,0,0.0,1,186.0,0,0.0,0,0.0,0,0.0
997,998,0,0.0,0,0.0,0,0.0,0,0.0,0,...,0,0.0,1,294.0,0,0.0,1,133.0,0,0.0
998,999,0,0.0,0,0.0,0,0.0,0,0.0,0,...,0,0.0,1,95.0,0,0.0,0,0.0,0,0.0
999,1000,1,301.0,0,0.0,0,0.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

In [217]:
# Question 6

qry = asql.question_6()
# qry = "SELECT DISTINCT(MonthName) FROM timeline"
with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

     CustomerID  Age  CorrectedAge  Gender
0             1   24            52  Female
1             2   34            71  Female
2             3   48            24  Female
3             4   34            34  Female
4             5   67            48  Female
..          ...  ...           ...     ...
995         996   39            77  Female
996         997   65            41  Female
997         998   52            39  Female
998         999   71            65  Female
999        1000   51            44    Male

[1000 rows x 4 columns]

In [222]:
# Question 7

qry = """

SELECT c.CustomerID, c.Age, c.CorrectedAge, c.Gender, c.AgeCategory, 
    -- Ranking 
    DENSE_RANK() OVER (PARTITION BY c.AgeCategory ORDER BY COALESCE(r.TotalRepayments, 0) DESC) AS "Rank"
    FROM corrected_customers c
    LEFT JOIN (
        SELECT CustomerID, COUNT(*) AS TotalRepayments
        FROM (SELECT DISTINCT * FROM repayments)
        GROUP BY CustomerID 
    ) r
    
        ON c.CustomerID = r.CustomerID
    ORDER BY c.AgeCategory, "Rank";

"""
# qry = "SELECT DISTINCT(MonthName) FROM timeline"
with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

     CustomerID  Age  CorrectedAge  Gender AgeCategory  Rank
0           995   41            33  Female       Adult     1
1           798   71            24  Female       Adult     2
2           725   21            35    Male       Adult     3
3           464   34            56    Male       Adult     3
4           698   29            21    Male       Adult     3
..          ...  ...           ...     ...         ...   ...
995         650   75            19    Male        Teen     7
996         596   71            19  Female        Teen     7
997         245   76            19    Male        Teen     7
998          41   53            18    Male        Teen     7
999         855   59            19  Female        Teen     8

[1000 rows x 6 columns]